// Package emit writes the two artifacts a training run produces: the C header
// the engines compile in, and a binary weight file.
//
// The header layout is a hard compatibility contract — six engines #include it
// and none of them parse anything but the #defines and the three arrays:
//
//	#define NN_H          <H>
//	#define NN_NUM_FEAT   <numFeat>
//	#define NN_W2_BUCKETS <buckets>          // OMITTED ENTIRELY when buckets == 1
//	static const int16_t NN_W1[NN_NUM_FEAT][NN_H] = { {...},\n ... };
//	static const int32_t NN_B1[NN_H] = {...};                       // one line
//	static const int16_t NN_W2[NN_W2_BUCKETS][NN_H] = { {...},\n ... };
//	                 ... or NN_W2[NN_H] = {...};  on one line when buckets == 1
//
// Values are plain decimals, comma separated, no spaces, and every row line
// ends with "}," including the last. Line endings are LF.
//
// Emitting NN_W2_BUCKETS for an engine whose search.c has no such branch is a
// COMPILE error in that engine (int16_t(*)[H] assigned to int16_t*). That is
// loud and therefore correct, but it is why variant.Buckets records what each
// kernel actually implements rather than what we would like it to.
package emit

import (
	"bufio"
	"encoding/binary"
	"fmt"
	"os"
	"strconv"

	"nnuetrainer/internal/model"
	"nnuetrainer/internal/variant"
)

// Header writes nnue_weights.h for the given quantized net.
func Header(path string, q *model.Quant, v *variant.Variant) error {
	var b []byte
	add := func(s string) { b = append(b, s...) }

	add("/* nnue_weights.h - generated by stand-alone-trainer (Go).\n")
	add(" * Antisymmetric net replacing the hand-tuned residue:\n")
	add(" *   f(b) = g(b) - g(mirror(b)),  g = 64 * W2 . crelu01(B1 + sum W1[feat])\n")
	add(" * " + v.FeatDoc + "\n")
	add(" * (X = up-moving side). Quantized: W1,W2 x256 int16; B1 x256 int32;\n")
	add(" * act clamp [0,256]; score16 = (W2.(a1-a2))/64 = 16x engine units.\n")
	add(fmt.Sprintf(" * variant=%s  anchor: man=%d king=%d (frozen, never learned).\n",
		v.Name, v.ValMan, v.ValKing))
	if q.Buckets > 1 {
		add(fmt.Sprintf(" * W2 has %d phase buckets on total piece count %v; piece count is\n",
			q.Buckets, v.PhaseCuts))
		add(" * mirror-invariant, so both accumulators share one W2 row and\n")
		add(" * antisymmetry is unaffected. search.c must use the SAME thresholds.\n")
	}
	add(" * Regenerate, never edit. */\n")

	add("#define NN_H " + strconv.Itoa(q.H) + "\n")
	add("#define NN_NUM_FEAT " + strconv.Itoa(q.NumFeat) + "\n")
	if q.Buckets > 1 {
		add("#define NN_W2_BUCKETS " + strconv.Itoa(q.Buckets) + "\n")
	}

	add("static const int16_t NN_W1[NN_NUM_FEAT][NN_H] = {\n")
	for f := 0; f < q.NumFeat; f++ {
		b = append(b, '{')
		for j := 0; j < q.H; j++ {
			if j > 0 {
				b = append(b, ',')
			}
			b = strconv.AppendInt(b, int64(q.W1[f*q.H+j]), 10)
		}
		add("},\n")
	}
	add("};\n")

	add("static const int32_t NN_B1[NN_H] = {")
	for j := 0; j < q.H; j++ {
		if j > 0 {
			b = append(b, ',')
		}
		b = strconv.AppendInt(b, int64(q.B1[j]), 10)
	}
	add("};\n")

	if q.Buckets == 1 {
		add("static const int16_t NN_W2[NN_H] = {")
		for j := 0; j < q.H; j++ {
			if j > 0 {
				b = append(b, ',')
			}
			b = strconv.AppendInt(b, int64(q.W2[j]), 10)
		}
		add("};\n")
	} else {
		add("static const int16_t NN_W2[NN_W2_BUCKETS][NN_H] = {\n")
		for k := 0; k < q.Buckets; k++ {
			b = append(b, '{')
			for j := 0; j < q.H; j++ {
				if j > 0 {
					b = append(b, ',')
				}
				b = strconv.AppendInt(b, int64(q.W2[k*q.H+j]), 10)
			}
			add("},\n")
		}
		add("};\n")
	}
	return os.WriteFile(path, b, 0644)
}

// ── binary weights ──────────────────────────────────────────────────────────
//
// A new magic is used deliberately. dama-cli's "DNN2" is a 16-byte header
// (H, numFeat, buckets) while international-dama-cli's "DNN2" is an 8-byte
// header carrying only H — the same magic for two incompatible layouts. NTW1
// carries the variant name so a russian net can never be silently loaded as a
// turkish one, and the legacy readers below disambiguate the old files by
// total size rather than trusting the magic.

const ntwMagic = "NTW1"

// Bin writes the quantized net in the NTW1 format.
func Bin(path string, q *model.Quant, v *variant.Variant) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	w := bufio.NewWriterSize(f, 1<<16)
	name := make([]byte, 16)
	copy(name, v.Name)
	w.WriteString(ntwMagic)
	w.Write(name)
	binary.Write(w, binary.LittleEndian, int32(q.H))
	binary.Write(w, binary.LittleEndian, int32(q.NumFeat))
	binary.Write(w, binary.LittleEndian, int32(q.Buckets))
	binary.Write(w, binary.LittleEndian, q.W1)
	binary.Write(w, binary.LittleEndian, q.B1)
	binary.Write(w, binary.LittleEndian, q.W2)
	return w.Flush()
}

// LoadBin reads NTW1, or any of the three legacy layouts. The variant supplies
// the feature count the legacy formats omit.
func LoadBin(path string, v *variant.Variant) (*model.Quant, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	if len(raw) < 8 {
		return nil, fmt.Errorf("%s: short file", path)
	}
	magic := string(raw[:4])

	type layout struct {
		name              string
		off               int
		h, numFeat, nBuck int
	}
	var cands []layout

	switch magic {
	case ntwMagic:
		if len(raw) < 32 {
			return nil, fmt.Errorf("%s: short NTW1 header", path)
		}
		gotName := string(raw[4 : 4+clen(raw[4:20])])
		if gotName != v.Name {
			return nil, fmt.Errorf("%s holds variant %q but --variant is %q", path, gotName, v.Name)
		}
		cands = append(cands, layout{"NTW1", 32,
			int(int32(binary.LittleEndian.Uint32(raw[20:]))),
			int(int32(binary.LittleEndian.Uint32(raw[24:]))),
			int(int32(binary.LittleEndian.Uint32(raw[28:])))})
	case "DNN2":
		// dama-cli / brazilian / turkish: 16-byte header.
		if len(raw) >= 16 {
			cands = append(cands, layout{"DNN2-16", 16,
				int(int32(binary.LittleEndian.Uint32(raw[4:]))),
				int(int32(binary.LittleEndian.Uint32(raw[8:]))),
				int(int32(binary.LittleEndian.Uint32(raw[12:])))})
		}
		// international: 8-byte header, H only, single W2.
		cands = append(cands, layout{"DNN2-8", 8,
			int(int32(binary.LittleEndian.Uint32(raw[4:]))), v.NumFeat, 1})
	case "DNN1":
		cands = append(cands, layout{"DNN1", 8,
			int(int32(binary.LittleEndian.Uint32(raw[4:]))), v.NumFeat, 1})
	default:
		return nil, fmt.Errorf("%s: bad magic %q", path, magic)
	}

	for _, c := range cands {
		if c.h <= 0 || c.numFeat <= 0 || c.nBuck <= 0 {
			continue
		}
		want := c.off + c.numFeat*c.h*2 + c.h*4 + c.nBuck*c.h*2
		if want != len(raw) {
			continue
		}
		if c.numFeat != v.NumFeat {
			return nil, fmt.Errorf("%s: %d features, but variant %s uses %d",
				path, c.numFeat, v.Name, v.NumFeat)
		}
		q := &model.Quant{
			H: c.h, NumFeat: c.numFeat, Buckets: c.nBuck, Mirror: v.Mirror(),
			W1: make([]int16, c.numFeat*c.h),
			B1: make([]int32, c.h),
			W2: make([]int16, c.nBuck*c.h),
		}
		p := c.off
		for i := range q.W1 {
			q.W1[i] = int16(binary.LittleEndian.Uint16(raw[p:]))
			p += 2
		}
		for i := range q.B1 {
			q.B1[i] = int32(binary.LittleEndian.Uint32(raw[p:]))
			p += 4
		}
		for i := range q.W2 {
			q.W2[i] = int16(binary.LittleEndian.Uint16(raw[p:]))
			p += 2
		}
		return q, nil
	}
	return nil, fmt.Errorf("%s: %s file does not match any known layout for variant %s "+
		"(size %d; check --variant and --h)", path, magic, v.Name, len(raw))
}

func clen(b []byte) int {
	for i, c := range b {
		if c == 0 {
			return i
		}
	}
	return len(b)
}
