// Package emit writes the two artifacts a training run produces: the C header
// the engines compile in, and a binary weight file.
//
// The header layout is a hard compatibility contract — six engines #include it
// and none of them parse anything but the #defines and the three arrays:
//
//	#define NN_H          <H>
//	#define NN_NUM_FEAT   <numFeat>
//	#define NN_W2_BUCKETS <buckets>          // OMITTED ENTIRELY when buckets == 1
//	static const int16_t NN_W1[NN_NUM_FEAT][NN_H] = { {...},\n ... };
//	static const int32_t NN_B1[NN_H] = {...};                       // one line
//	static const int16_t NN_W2[NN_W2_BUCKETS][NN_H] = { {...},\n ... };
//	                 ... or NN_W2[NN_H] = {...};  on one line when buckets == 1
//
// Values are plain decimals, comma separated, no spaces, and every row line
// ends with "}," including the last. Line endings are LF.
//
// Emitting NN_W2_BUCKETS for an engine whose search.c has no such branch is a
// COMPILE error in that engine (int16_t(*)[H] assigned to int16_t*). That is
// loud and therefore correct, but it is why variant.Buckets records what each
// kernel actually implements rather than what we would like it to.
package emit

import (
	"bufio"
	"encoding/binary"
	"fmt"
	"os"
	"strconv"

	"nnuetrainer/internal/model"
	"nnuetrainer/internal/variant"
)

// Header writes nnue_weights.h for the given quantized net.
func Header(path string, q *model.Quant, v *variant.Variant) error {
	if q.Chess {
		return headerChess(path, q, v)
	}
	var b []byte
	add := func(s string) { b = append(b, s...) }

	add("/* nnue_weights.h - generated by stand-alone-trainer (Go).\n")
	add(" * Antisymmetric net replacing the hand-tuned residue:\n")
	add(" *   f(b) = g(b) - g(mirror(b)),  g = 64 * W2 . crelu01(B1 + sum W1[feat])\n")
	add(" * " + v.FeatDoc + "\n")
	add(" * (X = up-moving side). Quantized: W1,W2 x256 int16; B1 x256 int32;\n")
	add(" * act clamp [0,256]; score16 = (W2.(a1-a2))/64 = 16x engine units.\n")
	add(fmt.Sprintf(" * variant=%s  anchor: man=%d king=%d (frozen, never learned).\n",
		v.Name, v.ValMan, v.ValKing))
	if q.Buckets > 1 {
		add(fmt.Sprintf(" * W2 has %d phase buckets on total piece count %v; piece count is\n",
			q.Buckets, v.PhaseCuts))
		add(" * mirror-invariant, so both accumulators share one W2 row and\n")
		add(" * antisymmetry is unaffected. search.c must use the SAME thresholds.\n")
	}
	add(" * Regenerate, never edit. */\n")

	add("#define NN_H " + strconv.Itoa(q.H) + "\n")
	add("#define NN_NUM_FEAT " + strconv.Itoa(q.NumFeat) + "\n")
	if q.Buckets > 1 {
		add("#define NN_W2_BUCKETS " + strconv.Itoa(q.Buckets) + "\n")
	}

	add("static const int16_t NN_W1[NN_NUM_FEAT][NN_H] = {\n")
	for f := 0; f < q.NumFeat; f++ {
		b = append(b, '{')
		for j := 0; j < q.H; j++ {
			if j > 0 {
				b = append(b, ',')
			}
			b = strconv.AppendInt(b, int64(q.W1[f*q.H+j]), 10)
		}
		add("},\n")
	}
	add("};\n")

	add("static const int32_t NN_B1[NN_H] = {")
	for j := 0; j < q.H; j++ {
		if j > 0 {
			b = append(b, ',')
		}
		b = strconv.AppendInt(b, int64(q.B1[j]), 10)
	}
	add("};\n")

	if q.Buckets == 1 {
		add("static const int16_t NN_W2[NN_H] = {")
		for j := 0; j < q.H; j++ {
			if j > 0 {
				b = append(b, ',')
			}
			b = strconv.AppendInt(b, int64(q.W2[j]), 10)
		}
		add("};\n")
	} else {
		add("static const int16_t NN_W2[NN_W2_BUCKETS][NN_H] = {\n")
		for k := 0; k < q.Buckets; k++ {
			b = append(b, '{')
			for j := 0; j < q.H; j++ {
				if j > 0 {
					b = append(b, ',')
				}
				b = strconv.AppendInt(b, int64(q.W2[k*q.H+j]), 10)
			}
			add("},\n")
		}
		add("};\n")
	}
	return os.WriteFile(path, b, 0644)
}

// headerChess writes chess-cli's nnue_weights.h, which is a DIFFERENT contract
// from the draughts one above. Its nnue.c reads four lowercase symbols:
//
//	static const int16_t nnue_w1[NNUE_IN*NNUE_HID];
//	static const int32_t nnue_b1[NNUE_HID];
//	static const int16_t nnue_w2[NNUE_HID];
//	static const int32_t nnue_b2;
//
// w1 is FLAT, not [in][hid], and there are no NN_H / NN_NUM_FEAT /
// NN_W2_BUCKETS defines -- nnue.c takes those from nnue.h, so emitting them
// here would be a redefinition. The byte layout mirrors n2h.c:49-76 (16 values
// per line, trailing comma on every value) so the two tools' output can be
// diffed directly; parity_chess.ps1 does exactly that.
func headerChess(path string, q *model.Quant, v *variant.Variant) error {
	if q.Buckets != 1 {
		return fmt.Errorf("chess header: buckets = %d, must be 1 "+
			"(its kernel has a single W2 row)", q.Buckets)
	}
	var b []byte
	add := func(s string) { b = append(b, s...) }

	add("/* nnue_weights.h - GENERATED by stand-alone-trainer (Go). Do not edit.\n")
	add(fmt.Sprintf(" * Quantized small NNUE (%d->%d->1), QA=%d QB=%d.\n",
		q.NumFeat, q.H, model.ChessQA, model.ChessQB))
	add(" * " + v.FeatDoc + "\n")
	add(" * The net is a RESIDUE on eval_classical(), not a replacement: the engine\n")
	add(" * computes eval_classical(pos) + nnue_eval(pos). Retrain with\n")
	add(" *   trainer --variant=chess ...   (anchor_parity.ps1 must pass first) */\n")
	add("#ifndef NNUE_WEIGHTS_H\n#define NNUE_WEIGHTS_H\n#include <stdint.h>\n\n")

	// 16 per line with a trailing comma on each, exactly as n2h.c does.
	flush16 := func(n int, get func(int) int64) {
		for i := 0; i < n; i++ {
			b = strconv.AppendInt(b, get(i), 10)
			b = append(b, ',')
			if i&15 == 15 {
				b = append(b, '\n')
			}
		}
		add("\n};\n\n")
	}

	add(fmt.Sprintf("static const int16_t nnue_w1[%d] = {\n", q.NumFeat*q.H))
	flush16(q.NumFeat*q.H, func(i int) int64 { return int64(q.W1[i]) })

	add(fmt.Sprintf("static const int32_t nnue_b1[%d] = {\n", q.H))
	flush16(q.H, func(i int) int64 { return int64(q.B1[i]) })

	add(fmt.Sprintf("static const int16_t nnue_w2[%d] = {\n", q.H))
	flush16(q.H, func(i int) int64 { return int64(q.W2[i]) })

	add(fmt.Sprintf("static const int32_t nnue_b2 = %d;\n\n", q.B2))
	add("#endif /* NNUE_WEIGHTS_H */\n")
	return os.WriteFile(path, b, 0644)
}

// NetBin writes chess-cli's own net.bin float format (tools/trainer.c:482-494,
// read back by tools/n2h.c:30-45):
//
//	int32 hdr[4] = { 0x4e4e5545 "NNUE", NNUE_IN, NNUE_HID, version }
//	float w1[in*hid]; float b1[hid]; float w2[hid]; float b2;
//
// version 2 = RESIDUE on eval_classical, 1 = legacy full-eval. This trainer
// only ever produces residue nets, so it always writes 2 -- chess-cli's
// trainer hard-refuses a cross-version warm start (trainer.c:258-265), which is
// exactly the protection we want to keep working.
//
// Writing this is not redundant with the .ntw: it is what lets chess-cli's
// existing n2h.exe re-quantize our float weights, giving parity_chess.ps1 a
// second, independent check of the whole quantization contract.
func NetBin(path string, m *model.Model) error {
	if !m.IsChess() {
		return fmt.Errorf("net.bin is a chess-only format (variant is %s)", m.V.Name)
	}
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	w := bufio.NewWriterSize(f, 1<<16)

	hdr := [4]int32{0x4e4e5545, int32(m.NumFeat), int32(m.H), 2}
	if err := binary.Write(w, binary.LittleEndian, hdr); err != nil {
		return err
	}
	put := func(vals []float64) error {
		buf := make([]float32, len(vals))
		for i, v := range vals {
			buf[i] = float32(v)
		}
		return binary.Write(w, binary.LittleEndian, buf)
	}
	if err := put(m.W1); err != nil {
		return err
	}
	if err := put(m.B1); err != nil {
		return err
	}
	if err := put(m.W2); err != nil {
		return err
	}
	if err := binary.Write(w, binary.LittleEndian, float32(m.B2)); err != nil {
		return err
	}
	return w.Flush()
}

// ── binary weights ──────────────────────────────────────────────────────────
//
// A new magic is used deliberately. dama-cli's "DNN2" is a 16-byte header
// (H, numFeat, buckets) while international-dama-cli's "DNN2" is an 8-byte
// header carrying only H — the same magic for two incompatible layouts. NTW1
// carries the variant name so a russian net can never be silently loaded as a
// turkish one, and the legacy readers below disambiguate the old files by
// total size rather than trusting the magic.

// NTW1 has no slot for an output bias, so chess gets NTW2 rather than a
// silently-longer NTW1. That is the whole lesson of the "DNN2" collision above:
// one magic, one layout.
const (
	ntwMagic   = "NTW1" // draughts
	ntwMagicV2 = "NTW2" // chess: same 32-byte header, plus a trailing int32 B2
)

// Bin writes the quantized net: NTW1 for draughts, NTW2 for chess.
func Bin(path string, q *model.Quant, v *variant.Variant) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	w := bufio.NewWriterSize(f, 1<<16)
	name := make([]byte, 16)
	copy(name, v.Name)
	magic := ntwMagic
	if q.Chess {
		magic = ntwMagicV2
	}
	w.WriteString(magic)
	w.Write(name)
	binary.Write(w, binary.LittleEndian, int32(q.H))
	binary.Write(w, binary.LittleEndian, int32(q.NumFeat))
	binary.Write(w, binary.LittleEndian, int32(q.Buckets))
	binary.Write(w, binary.LittleEndian, q.W1)
	binary.Write(w, binary.LittleEndian, q.B1)
	binary.Write(w, binary.LittleEndian, q.W2)
	if q.Chess {
		binary.Write(w, binary.LittleEndian, q.B2)
	}
	return w.Flush()
}

// LoadBin reads NTW1, or any of the three legacy layouts. The variant supplies
// the feature count the legacy formats omit.
func LoadBin(path string, v *variant.Variant) (*model.Quant, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	if len(raw) < 8 {
		return nil, fmt.Errorf("%s: short file", path)
	}
	magic := string(raw[:4])

	type layout struct {
		name              string
		off               int
		h, numFeat, nBuck int
		chess             bool // NTW2: a trailing int32 B2
	}
	var cands []layout

	switch magic {
	case ntwMagic, ntwMagicV2:
		if len(raw) < 32 {
			return nil, fmt.Errorf("%s: short %s header", path, magic)
		}
		gotName := string(raw[4 : 4+clen(raw[4:20])])
		if gotName != v.Name {
			return nil, fmt.Errorf("%s holds variant %q but --variant is %q", path, gotName, v.Name)
		}
		isChess := magic == ntwMagicV2
		// The magic and the descriptor must agree about the kernel, or the
		// weights would be read with the wrong forward pass and the wrong
		// quantization scale -- and still produce plausible numbers.
		if isChess != v.IsChess() {
			return nil, fmt.Errorf("%s is a %s (%s-kernel) file but variant %s uses the %s kernel",
				path, magic, kernelWord(isChess), v.Name, v.Kernel)
		}
		cands = append(cands, layout{name: magic, off: 32,
			h:       int(int32(binary.LittleEndian.Uint32(raw[20:]))),
			numFeat: int(int32(binary.LittleEndian.Uint32(raw[24:]))),
			nBuck:   int(int32(binary.LittleEndian.Uint32(raw[28:]))),
			chess:   isChess})
	case "DNN2":
		// dama-cli / brazilian / turkish: 16-byte header.
		if len(raw) >= 16 {
			cands = append(cands, layout{name: "DNN2-16", off: 16,
				h:       int(int32(binary.LittleEndian.Uint32(raw[4:]))),
				numFeat: int(int32(binary.LittleEndian.Uint32(raw[8:]))),
				nBuck:   int(int32(binary.LittleEndian.Uint32(raw[12:])))})
		}
		// international: 8-byte header, H only, single W2.
		cands = append(cands, layout{name: "DNN2-8", off: 8,
			h: int(int32(binary.LittleEndian.Uint32(raw[4:]))), numFeat: v.NumFeat, nBuck: 1})
	case "DNN1":
		cands = append(cands, layout{name: "DNN1", off: 8,
			h: int(int32(binary.LittleEndian.Uint32(raw[4:]))), numFeat: v.NumFeat, nBuck: 1})
	default:
		return nil, fmt.Errorf("%s: bad magic %q", path, magic)
	}

	for _, c := range cands {
		if c.h <= 0 || c.numFeat <= 0 || c.nBuck <= 0 {
			continue
		}
		want := c.off + c.numFeat*c.h*2 + c.h*4 + c.nBuck*c.h*2
		if c.chess {
			want += 4 // trailing int32 B2
		}
		if want != len(raw) {
			continue
		}
		if c.numFeat != v.NumFeat {
			return nil, fmt.Errorf("%s: %d features, but variant %s uses %d",
				path, c.numFeat, v.Name, v.NumFeat)
		}
		q := &model.Quant{
			H: c.h, NumFeat: c.numFeat, Buckets: c.nBuck,
			Chess:  c.chess,
			Mirror: v.Mirror(),
			W1:     make([]int16, c.numFeat*c.h),
			B1:     make([]int32, c.h),
			W2:     make([]int16, c.nBuck*c.h),
		}
		p := c.off
		for i := range q.W1 {
			q.W1[i] = int16(binary.LittleEndian.Uint16(raw[p:]))
			p += 2
		}
		for i := range q.B1 {
			q.B1[i] = int32(binary.LittleEndian.Uint32(raw[p:]))
			p += 4
		}
		for i := range q.W2 {
			q.W2[i] = int16(binary.LittleEndian.Uint16(raw[p:]))
			p += 2
		}
		if c.chess {
			q.B2 = int32(binary.LittleEndian.Uint32(raw[p:]))
		}
		return q, nil
	}
	return nil, fmt.Errorf("%s: %s file does not match any known layout for variant %s "+
		"(size %d; check --variant and --h)", path, magic, v.Name, len(raw))
}

func kernelWord(chess bool) string {
	if chess {
		return "chess"
	}
	return "draughts"
}

func clen(b []byte) int {
	for i, c := range b {
		if c == 0 {
			return i
		}
	}
	return len(b)
}
